spring:
  application:
    name: init-example-service
    server:
      port: ${PORT:8761}

    eureka:
      client:
        registerWithEureka: false
        fetchRegistry: false
      instance:
        hostname: my-eureka-server.com
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=postgres
    username: postgres
    password: admin
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  liquibase:
    default-schema: postgres
    liquibase-schema: public
    enabled: true
    user: postgres
    password: admin
    change-log: classpath:db/changelog/v1.0/changelog-v1.0.xml
